controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
# app_category_list:
#   path: /category
#   controller: App\Controller\CategoryController::list

# program_show:
#   path: "/program/{id}/"
#   controller: 'App\Controller\ProgramController::show'
#   methods: ["GET"]
#   requirements:
#     id: '\d+'

# program_category:
#   path: "/program/category/{id}"
#   controller: 'App\Controller\ProgramController::category'
#   methods: ["GET"]
# category:
#   resource: ../src/Controller/CategoryController.php
#   prefix: /category
#   type: annotation
